In [25]:
# Initial imports
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.ensemble import RandomForestRegressor

### Step 1: Read the data from the `Resources` folder into a Pandas DataFrame.

In [4]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
# YOUR CODE HERE!
df = pd.read_csv("../Web Scraping/predicting_house_price.csv")
df = df.drop("Unnamed: 0", axis =1)
# Review the DataFrame
# YOUR CODE HERE!
df.head()

,street,city,province,postal_code,fire_place,style,lat,lon,price,number_of_beds,number_of_baths,extra_space
0,6 HONEYBOURNE CRES,Markham,Ontario,L3P 1P3,1,Detached,43.856371,-79.337682,2998000,5,8,1
1,83 BOARDWALK DR,Toronto,Ontario,M4L 3X9,1,Detached,43.670890,-79.316931,2599900,3,4,0
2,2158 PINEVIEW DR,Oakville,Ontario,L6H 5M3,1,Detached,43.447436,-79.666672,1999000,5,4,0
3,4078 HWY #6 Highway S,Mount Hope,Ontario,L0R 1W0,1,Detached,43.156141,-79.916180,1425000,3,3,0
4,12 HERCULES CLUB DR,Richmond Hill,Ontario,L4K 1K6,1,Townhouse,43.880117,-79.439292,1199000,3,3,0

In [12]:
df_encoded = pd.get_dummies(df, columns=['city', 'style'])
df_encoded.head()

,street,province,postal_code,fire_place,lat,lon,price,number_of_beds,number_of_baths,extra_space,...,city_Waterdown,city_Waterloo,city_Welland,city_Whitby,city_Whitchurch-Stouffville,city_Windsor,city_Woodstock,style_Detached,style_Semi-Detached,style_Townhouse
0,6 HONEYBOURNE CRES,Ontario,L3P 1P3,1,43.856371,-79.337682,2998000,5,8,1,...,0,0,0,0,0,0,0,1,0,0
1,83 BOARDWALK DR,Ontario,M4L 3X9,1,43.670890,-79.316931,2599900,3,4,0,...,0,0,0,0,0,0,0,1,0,0
2,2158 PINEVIEW DR,Ontario,L6H 5M3,1,43.447436,-79.666672,1999000,5,4,0,...,0,0,0,0,0,0,0,1,0,0
3,4078 HWY #6 Highway S,Ontario,L0R 1W0,1,43.156141,-79.916180,1425000,3,3,0,...,0,0,0,0,0,0,0,1,0,0
4,12 HERCULES CLUB DR,Ontario,L4K 1K6,1,43.880117,-79.439292,1199000,3,3,0,...,0,0,0,0,0,0,0,0,0,1

In [13]:
# Define features set
data_x = df_encoded.drop(['street', 'province','postal_code', 'price', 'lat', 'lon'], axis =1)
y = df["price"].values.reshape(-1, 1)
X = data_x

In [14]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [15]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [16]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X_train)

In [17]:
# Scale the training data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [26]:
# Create the random forest classifier instance
rf_model = RandomForestRegressor(n_estimators=500, random_state=78)

In [28]:
# Fit the model and use .ravel()on the "y_train" data. 
rf_model = rf_model.fit(X_train_scaled, y_train.ravel())

In [29]:
# Making predictions using the testing data
predictions = rf_model.predict(X_test_scaled)

In [30]:
# Calculating the accuracy score
accuracy = rf_model.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: -3.928374952484228

C:\Users\yalda\anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(